sonar.projectKey=FortyTwo43_SmartTravel
sonar.projectName=SmartTravel
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Exclusions for seed files - S1192 (string duplication)
sonar.issue.ignore.multicriteria=sql_seed
sonar.issue.ignore.multicriteria.sql_seed.ruleKey=plsql:S1192
sonar.issue.ignore.multicriteria.sql_seed.resourceKey=**/seed.sql
